### ISSUE TITLE
Реализовать вычисление hash-функции на С

### ISSUE THREAD

**Issue by Croolis** [ADKosm/PostgreSQLSH#4]

**Comment by ADKosm** [comment]
@Croolis , я сейчас задумался, есть ли необходимость делать hash именно на C. В том смысле, что самая сложная операция в нем - это перемножение векторов, и оно реализовано на C. Генерация параметров тоже на С. В самой функции хеша остается лишь сложить два числа и поделить на третье. Мне кажется, что после #2 гораздо логичнее реализовать это на PL/pgSQL, так как на производительность это не повлияет, а вот абстракции буду гораздо выше, что потом проще использовать.
